#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install -y nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sudo ufw allow 'Nginx HTTP'
sudo sh -c "echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html"
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx reload
