#!/usr/bin/env bash
#prints fizz or buzz when the numbers is divisible by 3 and 5 respectively
for i in {1..100}; do
  if ((i % 3 == 0)) && ((i % 5 == 0)); then
    echo "FizzBuzz"
  elif ((i % 3 == 0)); then
    echo "Fizz"
  elif ((i % 5 == 0)); then
    echo "Buzz"
  else
    echo "$i"
  fi
done

